config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  get "contacts/new"
  # get "home/index"
  get "home/about"
  root to: "home#index"
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :correct_user, only: [ :edit, :update, :destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    # @contact = Contact.new
    @contact = current_user.contacts.build
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    # @contact = Contact.new(contact_params)
    @contact = current_user.contacts.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy!

    respond_to do |format|
      format.html { redirect_to contacts_path, status: :see_other, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # authenticate_user! is a method provided by Devise that requires a user to be logged in before accessing the action.
  def correct_user
    @contact = current_user.contacts.find_by(id: params[:id])
    redirect_to contacts_path, notice: "Not authorized to edit this contact" if @contact.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.expect(contact: [ :first_name, :last_name, :email, :Phone_number, :linkedin, :user_id ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # def index
  # end

  def about
  end

  def index
    @tasks = Task.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to tasks_path, status: :see_other, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.expect(task: [ :title, :description ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>" class-"jumbotron">
  <h1 class="display-4">
    <%= contact.first_name %>
    <%= contact.last_name %>
  </hi>
  <p class="lead">
    <%= contact.email %> |
    <%= contact.Phone_number %> |
    <%= contact.linkedin %>
  </p>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name,  class:"form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name,  class:"form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email,  class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :Phone_number, style: "display: block" %>
    <%= form.text_field :Phone_number,  class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :linkedin, style: "display: block" %>
    <%= form.text_field :linkedin,  class:"form-control" %>
  </div>
  <div class="field form-group">
    <%= form.number_field :user_id,
    id: :friend_user_id, class:"form-control",
    value:current_user.id, type: :hidden
    %>

  <br/>

  <div class="field form-group">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<% content_for :title, "Editing contact" %>

<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact, class: "btn btn-primary btn-sm"%> 
  <%= link_to "Back to contacts", contacts_path, class: "btn btn-dark btn-sm" %> 
  <%= button_to "Destroy", @contact, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm", form: { class: "d-inline" } %>
</div>

app/views/contacts/index.html.erb
 <% content_for :title, "Contacts" %> 

<%# <h1>Contacts</h1> %>

<%# <div id="contacts" > %>
  <%# <% @contacts.each do |contact| %> 
    <%# <%= render contact %> 
    <%# <p> %>
      <%# <%= link_to "Show this contact", contact %> 
    <%# </p> %>
  <%# <% end %>
<%# </div> %>


<div class="container mt-4">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h2>Contacts</h2>
    <%= link_to "New contact", new_contact_path, class: "btn btn-primary" %>
  </div>
  <table class="table table-hover">
    <thead class="thead-dark" style="background-color: #343a40;">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>User ID</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
        <% if contact.user == current_user %>
        <tr>
          <td>
            <%= link_to "#{contact.first_name} #{contact.last_name}", edit_contact_path(contact), class: "btn btn-link" %>
          </td>
          <td><%= contact.email %></td>
          <td><%= contact.Phone_number %></td>
          <td><%= contact.user_id %></td>
          <td>
            <%= button_to "Destroy", contact, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %> 
          </td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/contacts/new.html.erb
<% content_for :title, "New contact" %>

<h1>New contact</h1>

<%= render "form", contact: @contact, class:"field" %>

<br>

<div class="form-group">
  <%= link_to "Back to contacts", contacts_path, class:"btn btn-dark" %>
</div>

app/views/contacts/show.html.erb
<%= render @contact %>  

<table class="table table-striped">
  <tbody>
      <tr>
            <%= link_to "Edit this contact", edit_contact_path(@contact), class: "btn btn-primary btn-sm" %>
            &nbsp;
            <%= link_to "Back to contacts", contacts_path, class: "btn btn-secondary btn-sm" %>
            &nbsp;
            <%= button_to "Destroy", @contact, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
      </tr>
  </tbody>
</table>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Home', root_path, class: "nav-link me-3" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        </li>
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class: 'nav-link me-3' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle me-3" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        
        <% if user_signed_in?%>
                   
          <li class="nav-item">
            <%= link_to 'Add Contact', contacts_new_path, class: 'nav-link me-3' %>
          </li>
          <li class="nav-item">
           <%= link_to 'Contacts List', contacts_path, class: 'nav-link me-3' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: 'nav-link me-3' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link me-3' %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link me-3' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link me-3' %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<br/>

app/views/home/about.html.erb
<h1> All about page ...  </h>

app/views/home/index.html.erb
<h1>Task List</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td>
          <%= link_to 'Show', task %>
          <%= link_to 'Edit', edit_task_path(task) %>
          <%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title><%= content_for(:title) || "My First App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
  


    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
     <% if notice %>
      <%= render 'layouts/alert' %>
    <% end %>

    <%= render 'home/header'%>



    <div class="container">
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

</div>

app/views/tasks/edit.html.erb
<% content_for :title, "Editing task" %>

<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<h1>Task List</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td>
          <%= link_to 'Show', task %>
          <%= link_to 'Edit', edit_task_path(task) %>
          <%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<% content_for :title, "New task" %>

<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>